export const SEARCH_NAVBAR = "SEARCH_NAVBAR";
export const SEARCH_BRAND_NAVBAR = "SEARCH_BRAND_NAVBAR";
export const SEARCH_CHECKBOX = "SEARCH_CHECKBOX";
export const SEARCH_SLIDER = "SEARCH_SLIDER";
export const SEARCH_RATING = "SEARCH_RATING";
